---
name: Bundle-Perl-Critic
version: 0.02
author:
  - 'Jeffrey Thalhammer <thaljef@cpan.org>'
abstract: A CPAN bundle for Perl::Critic and related modules
license: perl
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Bundle::Perl::Critic:
    file: lib/Bundle/Perl/Critic.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
