---
name: Bundle-Perl-Critic
version: 0.01
author:
  - Jeffrey Thalhammer <thaljef@cpan.org>
abstract: A CPAN bundle for Perl::Critic and related modules
license: perl
resources:
  license: http://dev.perl.org/licenses/
provides:
  Bundle::Perl::Critic:
    file: lib/Bundle/Perl/Critic.pm
    version: 0.01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
